### ISSUE TITLE
where is the models？

### ISSUE THREAD

**Issue by majinmin** [WENGSYX/LingYi#1]
hi,up,thank for you project,but no mode i can find,please give me the models,thank you

**Comment by WENGSYX** [comment]
Hello, all models are uploaded to the huggingface. You can find it in https://huggingface.co/WENGSYX

**Comment by WENGSYX** [comment]
The  model file in code has been modified.

**Comment by majinmin** [comment]
> 

How do they correspond，（old and  new name）☺
example:
  FENZHEN_MODEL_NAME = 'fenzhen_BERT'
  CMDD_MODEL_NAME = 'CPT'
  BL_MODEL_NAME = 'BLCPT'     
![image](https://user-images.githubusercontent.com/19158661/192468531-1862ad50-5a37-42c5-ad3c-44fefa2cc9b3.png)

**Comment by WENGSYX** [comment]
The new code already contains the actual model name. You can review it again
