### ISSUE TITLE
对于非常规问题，模型表现非常不有好，请问作者是否对这类问题有做应对方法呢

### ISSUE THREAD

**Issue by listwebit** [WENGSYX/LingYi#3]
大佬好，对于特殊问题，如何避免错误的回答呢？
例如：
(1)高血压病人可以吃屎吗？模型的回答是：高血压病人是可以吃屎的，但是要注意不要吃得太多，因为大便里面含有大量的水分，会导致血压升高，所以在平常的时候一定要多吃一些新鲜的蔬菜和水果，这样可以有效的缓解血压的升高。
(2)高血压病人可以吃砖头吗？模型的回答是：高血压病人是可以吃砖头的，但是要注意不要吃太多，因为砖头含有大量的脂肪和胆固醇，这些都会导致血压升高，所以平时一定要多吃一些新鲜的蔬菜和水果。
对于模式：高血压病人可以吃XX吗？模型的回答全是可以吃，这种情况是不是可以修复呢？
期待大佬的回复

**Comment by WENGSYX** [comment]
在LingYi系统中，我们使用了演绎推理的方式获得了目标实体，但知识图谱有限而可能缺失关键实体，例如缺乏（“屎”—“能否食用”—""）这类三元组，在这种场景下就会转由模型自主进行推理。而全部回答可以吃，是由于神经网络模型可能在部分场景下面临语料稀缺的问题，无法准确推断。在未来，我们会进一步改进系统，增加额外的约束性。感谢您的意见。
